const AppConstants = {
  development: 'development',
  contactDetailsText: 'If you have any questions, please contact ',
  password: "password",
  reg: "REG",
  comp: "COMP",
  ftg: "FTG",
  competitionDivisionValidation: "If there are any players graded to this division, they will be unassigned.",
  competitionDivisionDeleteSuccess: "Competition division deleted successfully",
  ungraded: "Ungraded",
  affiliateNameOn: '$(Affiliate_Name) on',
  affiliateName: '$(Affiliate_Name)',
  userName: '${userName}',
  nameAndPassword: 'Your Username is ${userName} and your Password is <b> ${password}</b>.',
  userNameAndPassword: 'Your Username is ${userName} and your Password is <b> ${password}</b>.<br><br>',
  clickHereToRegister: 'Please <a href="$(url)">click here</a> to complete your registration.',
  competionName: '$(Competition_Name)',
  division: '$(division)',
  inDivision: 'in $(division)',
  teamName: '$(team_name)',
  startDate: '$(start_date)',
  endDate: '$(end_date)',
  password$: '${password}',
  registerPersonName: '$(registering_person_name)',
  registerPersonNumber: '$(registering_person_number)',
  userRegUniquekey: '{USERREGUNIQUEKEY}',
  regCloseDate: '$(registration_close_date)',
  name: '$(name)',
  url: '$(url)',
  listNameAndRole: '$(list_user_name_and_role)',
  replyName: '$(rego_form_contact_name)',
  replyEmail: '$(rego_form_contact_email)',
  replyPhone: '$(rego_form_contact_phone)',
  or: '$(or)',
  regFormAffiliateName: '$(rego_form_affiliate_name)',
  playerCouchUmpire : '$(player, coach, umpire)',
  childName: '$(child’s name)',
  anotherProduct:'You also made other registrations',
  productTemplate:'$(name) as a $(player, coach, umpire) for $(Competition_Name) with $(Affiliate_Name). Your Competition starts on $(start_date).<br><br>',
  singleUserMultipleComp: '$(player, coach, umpire) with $(Affiliate_Name) in $(Competition_Name).',

  productTemplateStartDate: '$(name) as a $(player, coach, umpire) with $(Affiliate_Name) in $(Competition_Name) starts on $(start_date).',
  coach: 'Coach',
  umpire: 'Umpire',
  coachRoleId: 17,
  umpireRoleId: 15,
  nonPlayerRoleId: 16,
  teamNameAlreadyExists: "Team name aleady exists",
  teamNameNotExists: "Team name not exists",
  errMessage:'Something went wrong. Please contact the administrator. ',
  singleCompValidationMsg: "{COMP_NAME}  allows for a player to register to one time only. {PLAYER_NAME} has already been registered to this competition.",
  singleCompDivValidationMsg: "{COMP_NAME} does not only allow a player to register to the same Division more than once. {PLAYER_NAME} has already registered to this division.",
  registration: "REGISTRATION",
  teamIndividual: "TEAMINDIVIDUAL",
  singleGame: "SINGLEGAME",
  instalment: "INSTALMENT",
  shop: "SHOP",
  teamMemberRegistration: 'TEAMMEMBERREGISTRATION',
  CASUAL_FEE: 1,
  SEASONAL_FEE: 2,
  SCHOOL_INVOICE:5,
  refererName: '$(referer_friend_name)',
  venue: '$(venue)',
  userMismatchError: ' A user with this {email} already exists, but the details you have entered do not match.',
  emailAlreadyInUse: ' {email} email is already in use. Please use a different email address.',
  emailMismatchError: '{email} email is incorrect.',
  DECLINED_DE_REGISTRATION: 2,
  PENDING_DE_REGISTRATION: 1,
  DE_REGISTERED: 3,
  successfullyInserted: "Successfully Inserted",
  deRegisterCourtTaken: "You cannot deregister once you have taken the court.",
  DECLINED: 3,
  INSTALMENT_FAILED: 6,
  paymentOptionInstalment: 5,
  date: '$(Date)',
  amount: '$(Amount)',
  dateAndAmount: '<br><br> $(Date) - $(Amount) <br><br> $(Date) - $(Amount)',
  yourPaymentIsDue: 'Your next payment(s) is due on:',
  finalPayment: 'This is your final payment.',
  stepInstalmentDirectDebit: 16,
  stepPerMatch: 17,
  card: "card",
  directDebit: "direct_debit",
  cash: "cash",
  cashCard: "cash_card",
  cashDirectDebit: "cash_direct_debit",
  succeeded: "succeeded",
  TRANSACTION_TYPE_REFUND: 1,
  compOrgName: "$(Comp_Org_Name)",
  newAffiliate: "$(New_Affiliate_Name)",
  organisationPhone: "$(organisation_phone)",
  PIN:"0101",
  VOUCHER_TYPE:"AK",
  singleCompTemplateWithoutUserName: 'You have successfully registered as $(player, coach, umpire) with $(Affiliate_Name) in $(Competition_Name).',
  singeCompTemplateWithUserName: 'You have successfully registered $(name) as $(player, coach, umpire) with $(Affiliate_Name) in $(Competition_Name).',
  DE_REGISTER: 1,
  TRANSFER: 2,
  APPROVED: 1,
  PARTIAL_APPROVED: 2,
  tableRows: "$(Table_rows)",
  requiredToPay: "be required to pay $(Amount)",
  refunded: "be refunded $(Amount)",
  notRequiredToPay: "not be required to pay a difference",
  transferTemplate: "$(Transfer_template)",
  competition: "competition",
  affiliate: "affiliate",
  membership: "membership",
  nomination: "nomination",
  charity: "charity",
  NOT_PAID: 1,
  PAID: 2,
  REDEEMED: 3,
  FAILED: 4,
  CASH_HANDLE: 5,
  PAY_AS_YOU_GO: 1,
  WEEKLY_INSTALMENT: 4,
  PAYMENT_METHOD_DD: 1,
  PAYMENT_METHOD_CC: 2,
  PAYMENT_METHOD_CH: 3,
  reason: '<th>Reason</th>',
  compeitionNameAndStartDate: '$(Competition_Name) starts on $(start_date).',
  youCanLoginToProfile: 'You can login and see your profile and activity at anytime by <a href="$(url)">clicking here</a>.',
  passThisEmailTo: 'You have used the same email to register yourself and your child $(names). Please note that your child will not receive a seperate email with their log in details. If you would like them to have their own log-in you will need to login to your profile and click on their name and change their email address. Then login as that user and click reset password.',
  passThisEmailTo1: 'Please pass this email onto $(names) to access Profile and Activity summary at anytime by <a href="$(url)">clicking here</a>.',
  names: '$(names)',
  PROCESSING: 3,
  member:'$(member)',
  installmentDateAndAmount: '$(installment_date_amount)',
  installmentPaymentDeductedOn: '<br> An Instalment payment for the competition Fees will  be deducted on: $(installment_date_amount)',
  registered: 'Registered',
  youPaid: 'You Paid',
  amountOwing: 'Amount owing',
  youHavePaidFor: 'You have Paid for -',
  youHaveNotPaidFor: 'You have Not Paid for -',
  notPaidMembers: '$(not_paid_members)',
  chargedIfNotPaidFees: '<br>As mentioned during registration if $(not_paid_members) fails to pay their fees prior to the commencement of the competition you will be charged any outstanding monies.',
  completeYouRegistration:'complete your registration',
  updateYourProfile: 'update your Profile',
  updateYourProfileTitle: 'Update your Profile',
  registerBoforeCloseDate: '<br><br>It’s important that you register before the registration close date of $(registration_close_date). $(Competition_Name) starts on $(start_date).',
  thankYouForRegDebitCard: '<br><br>Thank you for registering the team - $(team_name) with $(Affiliate_Name) in $(Competition_Name).',
  owing: 'OWING',
  paid: 'Paid',
  forTeamTeamName: 'for team - $(team_name)',
  exceedMessage: 'Registration Cap for the Membership Type is exceeded. Please select another Division / Competition.',
  activeKidServiceUnavailable:"The NSW Active Kids Portal is currently unavailable. Please try again later.",
  tooManyRequests: "The NSW Active Kids Portal is experiencing some delays. Please try again",
  eachPlayer: "Each player",
  perMatchFeeTemplate: " <br>Each player will be charged $(perMatchFee) at each match.",
  perMatchFee: '$(perMatchFee)',
  you: 'You',
  appName: '{{appName}}',
  youAndYour: 'you and your team member’s',
  your: 'your',
  colonAndDot: ':.',
  voucherPosIdNotConfigured: "Your organisation is not configured for Active Kids - please contact your administrator.",
  voucherPostalCodeNotConfigured: "Your organisation is not configured for Active Kids - please contact your administrator.",
  voucherStoreChannelCodeNotConfigured: "Your organisation is not configured for Active Kids - please contact your administrator.",
  invalidPinVoucher: 'The date of birth you’ve entered doesn’t match the date of birth for this voucher.',
  parentHasSameEmail: 'You have used the same email to register yourself as your parent/ guardian. Please note that the child/ parent will not receive a seperate email with their log in details. If you would like them to have their own log-in you will need to login to your profile and click on their name and change their email address. Then get them to  login as that user and click reset password.',
  childHasDiffEmail: '$(names) has been sent their username and password on $(email) and can log in at anytime to access their profile.',
  withParentEmailNote: '<tr><td colspan="2" class="ind-subtext">** Will not get their own login as you have provided the same email address as yourself. You can access their profile from your login to update their email address and then ask them to reset their password in order to get their own login.</td></tr>',
  childRegistererWithParentEmailNote: '<tr><td colspan="2" class="ind-subtext">** Will not get own login as you have provided the same email address as your parent. Your parent can switch to your profile and update your email address, then you can reset your password in order to get your own login.</td></tr>',
  otherMemberPrefix: "$(otherMembers)",
  otherMemberNoteSingle: '$(otherMembers) has been sent their username and password via email and can log in at anytime to access their profile.',
  otherMemberNote: '$(otherMembers) have been sent their username and password via email and can log in at anytime to access their profile.',
  umpireNote: 'Please update Umpire availability on profile, also (if applicable) add bank account details to receive payments for Umpiring duties.',
  parentsLogin: '(Parent`s login)',
  emailYou: 'email you',
  youSentence: 'you',
  email: 'email',
  instalmentVoucherMsg: 'Instalments can’t be used if a voucher has been applied. Please select another payment option.',

  pending: "pending",
  playerwsaDomain: 'player@wsa.com',

  // payments and card
  cardErrDefault: 'We could not process the payment, please check your card details.',
  cardDeclinedInsufficientFunds: 'This Payment could not be processed due to insufficient funds. Please contact you Bank.',
  cardDeclinedLostCard: 'Payment is blocked on this card',
  cardDeclinedStolenCard: 'Payment is blocked on this card',
  cardGenericDecline: 'Your card was declined. Please contact you Bank.',
  cardDeclined: 'Your card was declined. Please contact you Bank.',
  cardRiskLevel: 'This payment could not be processed. Please contact your Bank.',
  expiredCard: 'Your card was declined. Card is expired. Please contact your Bank.',
  cardIncorrectNumber: 'Your card was declined. Incorrect card number. Please contact your Bank',
  incorrectCVC: 'You have entered an incorrect CVC. Please check your details and try again.',
  cardProcessingError: 'This payment could not be processed. Please contact your Bank.',
  success: "Success",
  schoolInvoice: "school_invoice",
  governmentVoucher: "government_voucher",
  perMatch: "per_match",
  refundingWarningMsg: "A Refund is not permitted as a user can only be refunded the amount they paid. A government Voucher may have been applied for this user.",
};

export default AppConstants;
